heat_template_version: 2015-04-30

description: >
  To attach a key pair to an instance

parameters:
  key_pair_id:
      type: string
      description: The ID of a key pair. This could be a list, but currently, just keep it as one key pair
      default: kp-a56dds11
  instance_id:
      type: string
      description: The ID of an instance. This could be a list, but currently, just keep it as one key pair
      default: i-0xjmusae
  zone:
      type: string
      description: data center
      default: pek2

resources:
  key_attachment:
    type: COM::TwoFellows::KeyAttachment
    properties:
      key_pair_id: { get_param: key_pair_id }
      instance_id: { get_param: instance_id }
      zone: { get_param: zone }
