heat_template_version: 2015-04-30

description: >
  To create an instance in QingCloud

parameters:
  server_image_id:
    type: string
    description: image id
    default: trustysrvx64e
  login_mode:
      type: string
      description: login mode. For Linux, there are keypair and passwd; for windows, there is only passwd
      default: passwd
  login_passwd:
      type: string
      description:
      default: U8yx97xYw
  zone:
      type: string
      description: data center
      default: pek2            
  
resources:
  server:
    type: COM::TwoFellows::Server
    properties:
      image_id: { get_param: server_image_id }
      login_mode: { get_param: login_mode  }
      login_passwd: { get_param: login_passwd }
      zone: { get_param: zone }

outputs:
  instance_id:
    description: ID of an instance
    value: { get_attr: [ server, instance_id ] }