heat_template_version: 2015-04-30

description: >
  To create an SSH Key pair in QingCloud

parameters:
  zone:
      type: string
      description: data center
      default: pek2
  key_pair_name:
      type: string
      description: the name of hte key pair
      default: ''


resources:
  key:
    type: COM::TwoFellows::Key
    properties:
      zone: { get_param: key_pair_zone }
      name: { get_param: key_pair_name }

outputs:
  pub_key:
    description: public key
    value: { get_attr: [ key, pub_key ] }
  private_key:
    description: private key
    value: { get_attr: [ key, private_key ] }